apis/urls.py
# from django.urls import path, include
# from rest_framework import routers
#
# from apis.views import ProductApiViewSet
#
# # DefaultRouter クラスのインスタンスを代入
# defaultRouter = routers.DefaultRouter()
# # userInfo/ にUserInfoViewSetをルーティングする
# defaultRouter.register('productApi', ProductApiViewSet)
#
# app_name = 'apis'
# urlpatterns = [
#     # defaultRouter をinclude する
#     path('api/', include(defaultRouter.urls)),
# ]

mitsuki_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from apis.views import ProductApiViewSet

# DefaultRouter クラスのインスタンスを代入
defaultRouter = routers.DefaultRouter()
# userInfo/ にUserInfoViewSetをルーティングする
defaultRouter.register('productApi', ProductApiViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('store_main/', include('store_main.urls')),
    path('api/', include(defaultRouter.urls)),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

store_main/urls.py
from django.urls import path
from store_main import views

app_name = 'store_main'
urlpatterns = [
    path('store_index/', views.store_index, name='store_index'),
    path('product_new/', views.product_new, name='product_new'),
    path('product_list/', views.product_list, name='product_list'),
    path('product_edit/<int:product_id>', views.product_edit,
         name='product_edit'),
    path('product_csv/', views.product_csv, name='product_csv'),
    path('test_index/', views.test_index, name='test_index'),
]

store_main/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Product(models.Model):
    """商品"""
    name = models.CharField(verbose_name='商品名', max_length=128)
    description = models.TextField(verbose_name='商品説明', max_length=5000,
                                   blank=True, default='')
    price = models.PositiveIntegerField(verbose_name='価格', blank=True,
                                        default=0)
    amount = models.PositiveIntegerField(verbose_name='在庫数', blank=True,
                                         default=0)
    image = models.ImageField(verbose_name='商品画像', upload_to='product', )
    code = models.CharField(verbose_name='商品コード', max_length=128, )

    # adminでの表示名
    def __str__(self):
        return self.name


class Sale(models.Model):
    """売上情報"""
    # https://itc.tokyo/django/foreignkey/
    # Productモデルと多対一の関係を作る
    product = models.ForeignKey(Product, on_delete=models.PROTECT,
                                verbose_name='商品名', )
    # https://qiita.com/Quest_love33/items/77c5cbf3acd2c09edd0a
    # 使用しているUserモデルと多対一の関係を作る
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT,
                             verbose_name='ユーザー名', )
    amount = models.PositiveIntegerField(verbose_name="購入個数", default=0)
    price = models.PositiveIntegerField(verbose_name='商品単価', default=0)
    total_price = models.PositiveIntegerField(verbose_name='小計', default=0)
    zip_code = models.CharField(verbose_name='郵便番号', max_length=128,
                                blank=True, default='')
    address = models.CharField(verbose_name='住所', max_length=128, blank=True,
                               default='')
    created_at = models.DateTimeField(verbose_name='販売日', auto_now=True)


class ImageZip(models.Model):
    """
    zipファイル受け入れ用モデル
    https://stackoverflow.com/questions/37234473/django-admin-images-in-zip-file-and-inserting-each-image-info-in-a-database
    """
    zip_import = models.FileField(blank=True, upload_to='image_zip',
                                  help_text='※画像のzipファイルをアップロードしてください。')

store_main/forms.py
from django import forms
from store_main.models import Product, ImageZip


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'amount', 'image', 'code',)


class CsvUploadForm(forms.Form):
    file = forms.FileField(label='CSVファイル', help_text='※拡張子csvのファイルをアップロードしてください。')


class ImageZipForm(forms.ModelForm):
    class Meta:
        model = ImageZip
        fields = ('zip_import',)

store_main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings

from store_main.models import Product, ImageZip
from main.views import index
from store_main.forms import ProductForm, CsvUploadForm, ImageZipForm
from apis.serializers import ProductSerializer

import csv
import io
import os
import glob
import shutil


def test_index(request):
    serializer = ProductSerializer()
    print(serializer.data)
    context = {}
    return render(request, template_name="store_main/test_index.html",
                  context=context)


def store_index(request):
    # スーパーユーザーでない場合。
    if not request.user.is_superuser:
        return redirect('main:index')

    context = {}
    return render(request, template_name="store_main/store_index.html",
                  context=context)


def product_new(request):
    # スーパーユーザーでない場合
    if not request.user.is_superuser:
        return redirect('main:index')

    if request.method == 'POST':
        # フォームのhtmlとファイルを受け取る
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            messages.add_message(request, messages.SUCCESS,
                                 "商品を登録しました。")
            redirect('store_main:product_list')
        else:
            messages.add_message(request, messages.ERROR,
                                 "商品登録に失敗しました。")
    # GETの場合
    form = ProductForm()

    context = {
        'form': form,
    }
    return render(request, template_name="store_main/product_new.html",
                  context=context)


# ストア側の商品一覧ページ
def product_list(request):
    # スーパーユーザーでない場合
    if not request.user.is_superuser:
        return redirect('main:index')

    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, template_name="store_main/product_list.html",
                  context=context)


# 商品削除
def product_delete(request, product_id):
    # スーパーユーザーでない場合
    if not request.user.is_superuser:
        return redirect('main:index')

    # 該当商品読み込み
    product = get_object_or_404(Product, pk=product_id)
    # 商品削除
    product.delete()
    messages.add_message(request, messages.SUCCESS,
                         "削除を完了しました。")

    return redirect('store_main:product_list')


# ストア側の商品編集ページ
def product_edit(request, product_id):
    # スーパーユーザーでない場合
    if not request.user.is_superuser:
        return redirect('main:index')

    product = get_object_or_404(Product, pk=product_id)
    # formを入力済みの状態で表示
    form = ProductForm(
        initial={
            'name': product.name,
            'description': product.description,
            'price': product.price,
            'amount': product.amount,
            'image': product.image,
            'code': product.code,
        }
    )
    if request.method == 'POST':
        if "product_edit" in request.POST:
            # 商品編集ボタンが押された場合
            form = ProductForm(request.POST, instance=product, )
            # 検証
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS,
                                     "編集を完了しました。")
                return redirect('store_main:product_edit',
                                product_id=product_id)
            else:
                messages.add_message(request, messages.ERROR,
                                     "編集に失敗しました。")

        if "product_delete" in request.POST:
            # 商品削除ボタンが押された場合
            return product_delete(request, product_id)

    # GET の場合
    context = {
        'product': product,
        'form': form,
    }
    return render(request, template_name="store_main/product_edit.html",
                  context=context)


# ストア側のcsv商品登録・編集機能
# https://blog.narito.ninja/detail/60/
def product_csv(request):
    # スーパーユーザーでない場合
    if not request.user.is_superuser:
        return redirect('main:index')

    # POSTの場合
    if request.method == 'POST':
        # product_csvが含まれている場合
        if 'product_csv' in request.POST:

            # フォームのhtmlとファイルを受け取る
            csv_form = CsvUploadForm(request.POST, request.FILES)

            if csv_form.is_valid():
                """ 商品csvアップ機能 """
                # csv.readerに渡すため、TextIOWrapperでテキストモードなファイルに変換
                csvfile = io.TextIOWrapper(csv_form.cleaned_data['file'],
                                           encoding='utf-8')
                reader = csv.reader(csvfile)
                # 1行ずつ取り出し、作成していく
                for i, row in enumerate(reader):
                    if i == 0:
                        continue
                    product, created = Product.objects.update_or_create(
                        code=row[0])
                    product.name = row[1]
                    product.description = row[2]
                    product.price = row[3]
                    product.amount = row[4]
                    product.image = f'product/{row[5]}'
                    product.save()
                messages.add_message(request, messages.SUCCESS,
                                     "追加・編集を完了しました。")
                return redirect('store_main:product_csv')
            else:
                messages.add_message(request, messages.ERROR,
                                     "追加・編集が失敗しました。")
                return redirect('store_main:product_csv')

        if 'product_img_zip' in request.POST:
            """ 画像zipアップ機能 """
            # フォームのhtmlとファイルを受け取る
            image_zip_form = ImageZipForm(request.POST, request.FILES)
            if image_zip_form.is_valid():
                image_zip = image_zip_form.save(commit=False)
                # zipを保存
                image_zip.save()
                # zipを展開
                shutil.unpack_archive(
                    glob.glob(os.path.join(settings.MEDIA_ROOT, 'image_zip',
                                           '*.zip'))[-1],
                    os.path.join(settings.MEDIA_ROOT, 'product'),
                )
                # ImageZipのレコードを全て削除
                ImageZip.objects.all().delete()
                # ディレクトリごとzipファイルを削除
                shutil.rmtree(os.path.join(settings.MEDIA_ROOT, 'image_zip'))

                messages.add_message(request, messages.SUCCESS,
                                     "画像アップロードを完了しました。")
                return redirect('store_main:product_csv')
            else:
                messages.add_message(request, messages.ERROR,
                                     "画像アップロードが失敗しました。")
                return redirect('store_main:product_csv')

    # GETの場合
    csv_upload_form = CsvUploadForm()
    image_zip_form = ImageZipForm()

    context = {
        'csv_upload_form': csv_upload_form,
        'image_zip_form': image_zip_form,
    }
    return render(request, template_name='store_main/product_csv.html',
                  context=context)

store_main/templates/store_main/product_csv.html
{% extends 'store_base.html' %}

{% block content %}
product_csv
<div class="container my-3">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ csv_upload_form.as_p }}
        <button type="submit" class="btn btn-primary" name="product_csv">
            csvアップロード
        </button>
    </form>
</div>
<div class="container my-3">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            画像zipファイル: {{ image_zip_form.zip_import }}{{ image_zip_form.zip_import.help_text }}
        </p>
        <button type="submit" class="btn btn-primary" name="product_img_zip">
            画像zipアップロード
        </button>
    </form>
</div>
{% endblock content %}

store_main/templates/store_main/product_edit.html
{% extends 'store_base.html' %}

{% block content %}
product_edit
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        {{ form.name.label_tag }}
        {{ form.name }}
    </p>
    <p>
        {{ form.description.label_tag }}
        {{ form.description }}
    </p>
    <p>
        {{ form.price.label_tag }}
        {{ form.price }}
    </p>
    <p>
        {{ form.amount.label_tag }}
        {{ form.amount }}
    </p>
    <p>
        {{ form.image.label_tag }}
        {{ form.image }}
    </p>
    <p hidden>
        {{ form.code.label_tag }}
        {{ form.code }}
    </p>
    <input type="submit" name="product_edit"
           value="商品編集">
    <input type="submit" name="product_delete"
           value="商品削除">
</form>
{% endblock content %}

store_main/templates/store_main/product_list.html
{% extends 'store_base.html' %}

{% block content %}

<div class="container store-product-container">
    <div class="container">
        {% for product in products %}
        <div class="card mx-auto store-card my-3" style="width: 60rem; max-width: 100%;">
            <div class="row no-gutters store-card">
                <a href="{% url 'store_main:product_edit' product.id %}"></a>
                <div class="col-md-4 my-auto">
                    <img class="card-img cart-img store-card-img-top"
                         src="{{ product.image.url }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="store-product-content mb-1">
                            <h6 class="card-title">{{ product.name }}</h6>
                            価格：{{ product.price }}円
                            <br>
                            在庫数：{{ product.amount }}個
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

store_main/templates/store_main/product_new.html
{% extends 'store_base.html' %}

{% block content %}
product_new
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        {{ form.code.label_tag }}
        {{ form.code }}
    </p>
    <p>
        {{ form.name.label_tag }}
        {{ form.name }}
    </p>
    <p>
        {{ form.description.label_tag }}
        {{ form.description }}
    </p>
    <p>
        {{ form.price.label_tag }}
        {{ form.price }}
    </p>
    <p>
        {{ form.amount.label_tag }}
        {{ form.amount }}
    </p>
    <p>
        {{ form.image.label_tag }}
        {{ form.image }}
    </p>
    <input type="submit" name="product_new"
                                   value="新規登録">
</form>
{% endblock content %}

store_main/templates/store_main/store_index.html
{% extends 'store_base.html' %}

{% block content %}

<div class="card mx-auto my-2" style="width: 60rem; max-width: 100%;">
    <div class="card-body store-card">
        <a href="{% url 'store_main:product_new' %}"></a>
        <h4 class="card-title">新規商品登録</h4>
        <p class="card-text">新しい商品を登録します。</p>
    </div>
</div>
<div class="card mx-auto my-2" style="width: 60rem; max-width: 100%;">
    <div class="card-body store-card">
        <a href="{% url 'store_main:product_list' %}"></a>
        <h4 class="card-title">商品一覧・編集・削除</h4>
        <p class="card-text">商品名・説明・画像・価格・在庫の編集・削除を行います。</p>
    </div>
</div>
<div class="card mx-auto my-2" style="width: 60rem; max-width: 100%;">
    <div class="card-body store-card">
        <a href="{% url 'store_main:product_csv' %}"></a>
        <h4 class="card-title">商品csv追加・編集</h4>
        <p class="card-text">csvによる商品名・説明・価格・在庫の編集を行います。</p>
    </div>
</div>
{% endblock content %}

store_main/templates/store_main/test_index.html
eee