apis/urls.py
# from django.urls import path, include
# from rest_framework import routers
#
# from apis.views import ProductApiViewSet
#
# # DefaultRouter クラスのインスタンスを代入
# defaultRouter = routers.DefaultRouter()
# # userInfo/ にUserInfoViewSetをルーティングする
# defaultRouter.register('productApi', ProductApiViewSet)
#
# app_name = 'apis'
# urlpatterns = [
#     # defaultRouter をinclude する
#     path('api/', include(defaultRouter.urls)),
# ]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('test_index/', views.test_index, name='test_index'),
    path('', views.index, name='index'),
    path('product_detail/<int:product_id>/', views.product_detail,
         name='product_detail'),
    path('user_cart/', views.user_cart, name='user_cart'),
    path('change_product_amount/', views.change_product_amount, name='change_product_amount'),
    path('order_history/', views.order_history, name='order_history'),
    # 決済
    path('payment/', views.payment, name="payment"),
    path('thanks/', views.thanks, name="thanks"),
]

mitsuki_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from apis.views import ProductApiViewSet

# DefaultRouter クラスのインスタンスを代入
defaultRouter = routers.DefaultRouter()
# userInfo/ にUserInfoViewSetをルーティングする
defaultRouter.register('productApi', ProductApiViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('store_main/', include('store_main.urls')),
    path('api/', include(defaultRouter.urls)),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

store_main/urls.py
from django.urls import path
from store_main import views

app_name = 'store_main'
urlpatterns = [
    path('store_index/', views.store_index, name='store_index'),
    path('product_new/', views.product_new, name='product_new'),
    path('product_list/', views.product_list, name='product_list'),
    path('product_edit/<int:product_id>', views.product_edit,
         name='product_edit'),
    path('product_csv/', views.product_csv, name='product_csv'),
    path('test_index/', views.test_index, name='test_index'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'
urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

templates/base.html
<!doctype html>
{% load django_bootstrap5 %}
{% load static %}
{% load humanize %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MitsukiStore</title>
    {% bootstrap_css %}
    <link rel="stylesheet"
          href="{% static 'css/style.css' %}?<?php date_default_timezone_set('Asia/Tokyo'); echo date('ymdHis',filemtime('{% static 'css/style.css' %}')); ?>"/>
    {% bootstrap_javascript %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand"
               href="{% url 'main:index' %}">MitsukiStore</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end"
                 id="navbarNav">
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}
                    {% if user.is_superuser %}
                    <li class="nav-item h4 mx-4">
                        <a class="nav-link active"
                           href="{% url 'store_main:store_index' %}">ストア管理画面へ</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="#">Point: {{ user.point }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'main:user_cart' %}">カート</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'main:order_history' %}">注文履歴</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}"
                           tabindex="-1"
                           aria-disabled="true">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}"
                           tabindex="-1"
                           aria-disabled="true">ログイン</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}"
                           tabindex="-1"
                           aria-disabled="true">新規登録</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

</header>
<div class="container">
    {% for message in messages %}
    <!--<div {% if message.tags %}class="{{ message.tags }}"{% endif %}> エラー？-->
    {% if message.tags %}
    <div class="{{ message.tags }}">
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

templates/payment.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <script src="https://js.stripe.com/v3/"></script>
    </head>
    <body>
        <!--inputタグでclient_secretを渡す→JavaScriptで値を取得する-->
        <input type="hidden" id="client_secret" value="{{ client_secret }}">

        <!--フォームが読み込まれたら、Payment Elementのインスタンスを作成して、それをコンテナーのDOMノードにマウントする-->
        <form id="payment-form">
            <div id="payment-element">
                <!-- Elements will create form elements here -->
            </div>
            <p>お支払い金額：{{ amount }}円</p>
            <button id="submit">支払いを確定する</button>
            <div id="error-message">
            <!-- Display error message to your customers here -->
            </div>
        </form>

        <script src="{% static 'js/stripe.js' %}"></script>
    </body>

templates/store_base.html
<!doctype html>
{% load django_bootstrap5 %}
{% load static %}
{% load humanize %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MitsukiStore</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}?<?php date_default_timezone_set('Asia/Tokyo'); echo date('ymdHis',filemtime('{% static 'css/style.css' %}')); ?>"/>
    {% bootstrap_javascript %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
        <div class="container-fluid">
            <a class="navbar-brand"
               href="{% url 'store_main:store_index' %}">ストア商品管理</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        </div>
    </nav>

</header>
<div class="container">
    {% for message in messages %}
    {% if message.tags %}
    <div class="{{ message.tags }}">
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

templates/thanks.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <p>お支払い完了</p>
    </body>