apis/urls.py
# from django.urls import path, include
# from rest_framework import routers
#
# from apis.views import ProductApiViewSet
#
# # DefaultRouter クラスのインスタンスを代入
# defaultRouter = routers.DefaultRouter()
# # userInfo/ にUserInfoViewSetをルーティングする
# defaultRouter.register('productApi', ProductApiViewSet)
#
# app_name = 'apis'
# urlpatterns = [
#     # defaultRouter をinclude する
#     path('api/', include(defaultRouter.urls)),
# ]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('test_index/', views.test_index, name='test_index'),
    path('', views.index, name='index'),
    path('product_detail/<int:product_id>/', views.product_detail,
         name='product_detail'),
    path('user_cart/', views.user_cart, name='user_cart'),
    path('change_product_amount/', views.change_product_amount, name='change_product_amount'),
    path('order_history/', views.order_history, name='order_history'),
    # 決済
    path('payment/', views.payment, name="payment"),
    path('thanks/', views.thanks, name="thanks"),
]

mitsuki_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from apis.views import ProductApiViewSet

# DefaultRouter クラスのインスタンスを代入
defaultRouter = routers.DefaultRouter()
# userInfo/ にUserInfoViewSetをルーティングする
defaultRouter.register('productApi', ProductApiViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('store_main/', include('store_main.urls')),
    path('api/', include(defaultRouter.urls)),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

main/models.py
from django.db import models
# from django.contrib.auth import get_user_model
#
#
# class Product(models.Model):
#     """商品"""
#     name = models.CharField(verbose_name='商品名', max_length=128)
#     description = models.TextField(verbose_name='商品説明', max_length=5000,
#                                    blank=True, default='')
#     price = models.PositiveIntegerField(verbose_name='価格')
#     amount = models.PositiveIntegerField(verbose_name='在庫数', default=0)
#     image = models.ImageField(verbose_name='商品画像', upload_to='product',
#                               blank=True, default='')
#     code = models.CharField(verbose_name='商品コード', max_length=128)
#
#     # adminでの表示名
#     def __str__(self):
#         return self.name
#
#
# class Sale(models.Model):
#     """売上情報"""
#     # https://itc.tokyo/django/foreignkey/
#     # Productモデルと多対一の関係を作る
#     product = models.ForeignKey(Product, on_delete=models.PROTECT,
#                                 verbose_name='商品名', )
#     # https://qiita.com/Quest_love33/items/77c5cbf3acd2c09edd0a
#     # 使用しているUserモデルと多対一の関係を作る
#     user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT,
#                              verbose_name='ユーザー名', )
#     amount = models.PositiveIntegerField(verbose_name="購入個数", default=0)
#     price = models.PositiveIntegerField(verbose_name='商品単価', default=0)
#     total_price = models.PositiveIntegerField(verbose_name='小計', default=0)
#     zip_code = models.CharField(verbose_name='郵便番号', max_length=128,
#                                 blank=True, default='')
#     address = models.CharField(verbose_name='住所', max_length=128, blank=True,
#                                default='')
#     created_at = models.DateTimeField(verbose_name='販売日', auto_now=True)

main/forms.py
from django import forms


class AddToCartForm(forms.Form):
    # 取り出しの際にnumが辞書型のキーなり、入力された数値が値となる
    num = forms.IntegerField(
        label='数量',
        min_value=1,
        required=True
    )


class PurchaseForm(forms.Form):
    zip_code = forms.CharField(
        label='郵便番号',
        max_length=7,
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': '数字7桁（ハイフンなし）'}
        )
    )

    address = forms.CharField(
        label='住所', max_length=100, required=False
    )


class TestForm(forms.Form):
    test = forms.CharField()

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from users.models import User
from store_main.models import Product, Sale
from main.forms import AddToCartForm, PurchaseForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings
# https://www.teamxeppet.com/pycharm-module-not-found-error/
import stripe
import json
import requests


# モデル出力確認
def test_index(request):
    # モデルの要素を取得
    users = User.objects.all().values()
    products = Product.objects.all().values()
    sales = Sale.objects.all().values()

    context = {
        'users': users,
        'products': products,
        'sales': sales,
    }
    return render(request, template_name='main/test_index.html',
                  context=context)


# トップページ、商品の一覧表示
def index(request):
    products = Product.objects.all().order_by('-code')
    # ページネーション
    paginator = Paginator(products, 6)
    page = request.GET.get('page', 1)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)
    context = {
        'pages': pages
    }
    return render(request, template_name='main/index.html', context=context)


# 商品詳細ページ
def product_detail(request, product_id):
    # 　product_idが存在しない場合404
    product = get_object_or_404(Product, pk=product_id)

    # カートに追加
    if request.method == 'POST':
        add_cart_form = AddToCartForm(request.POST)
        # 検証
        if add_cart_form.is_valid():
            # formのnum取り出し
            num = add_cart_form.cleaned_data['num']
            # sessionにcartが含まれているか確認
            if 'cart' in request.session:
                # 既に対象のproduct_idがcartにあれば加算、なければ新しくキーを追加する
                if str(product_id) in request.session['cart']:
                    request.session['cart'][str(product_id)] += num
                else:
                    request.session['cart'][str(product_id)] = num

            # sessionにcartが含まれていない場合
            else:
                # 新しく'cart'というキーをセッションに追加する
                request.session['cart'] = {str(product_id): num}
            # メッセージの出力
            messages.success(request, f'{product.name}を{num}個カートに入れました!')
            return redirect('main:product_detail', product_id=product_id)

    # GET
    add_cart_form = AddToCartForm()
    context = {
        'product': product,
        'add_cart_form': add_cart_form,
    }
    return render(request, template_name='main/product_detail.html',
                  context=context)


# 住所検索の関数
def fetch_address(zip_code):
    """郵便番号検索APIを利用する関数
    引数に指定された郵便番号に対応する住所を返す
    住所取得に失敗した場合じゃ空文字を返す"""

    REQUEST_URL = f'http://zipcloud.ibsnet.co.jp/api/search?zipcode={zip_code}'
    response = requests.get(REQUEST_URL)
    response = json.loads(response.text)
    results, api_status = response['results'], response['status']

    address = ''
    # レスポンスステータスが200　かつ　'results'が存在する場合
    # address変数に取得した住所を代入する
    if api_status == 200 and results is not None:
        result = results[0]
        address = result['address1'] + result['address2'] + result['address3']
    return address


# カートページ
@login_required
def user_cart(request):
    # GET POST 両方の変数＝＝＝＝＝＝＝＝＝＝＝＝

    # session自体が辞書型になっているので.getで'cart'キーでcartの辞書を取得、
    # cartがない場合は空の辞書とする。
    cart = request.session.get('cart', {})

    # 空の辞書とtotal_priceの変数を用意
    cart_products = {}
    total_price = 0

    # 合計金額の計算
    # .items()でkeyとvalueを取り出す
    for product_id, num in cart.items():
        product = Product.objects.filter(id=product_id).first()

        # .first()で削除されている商品の場合はNoneを返す
        if product is None:
            continue

        # cart_productsにproductをkeyとしてnumを追加
        cart_products[product] = num
        total_price += product.price * num

    # ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

    if request.method == 'POST':

        # user情報
        user = request.user

        purchase_form = PurchaseForm(request.POST)

        if purchase_form.is_valid():

            # 住所検索ボタンが押下された場合
            if 'search_address' in request.POST:
                zip_code = request.POST['zip_code']
                address = fetch_address(zip_code)

                # 住所が取得できなかった場合はメッセージを出してリダイレクト
                if not address:
                    messages.warning(request, "住所を取得できませんでした")
                    return redirect('main:user_cart')

                # 住所が取得出来たらフォームの値として入力する
                purchase_form = PurchaseForm(
                    initial={'zip_code': zip_code, 'address': address}
                )
                context = {
                    'purchase_form': purchase_form,
                    'cart_products': cart_products,
                    'total_price': total_price,
                }
                return render(request, template_name='main/user_cart.html',
                              context=context)

        # 購入ボタンを押された場合
        if 'buy_product' in request.POST:

            # 住所が入力済みか確認する。未入力の場合はリダイレクトする。
            if not purchase_form.cleaned_data['address']:
                messages.warning(request, "住所の入力は必須です")
                return redirect('main:user_cart')

            # カートが空じゃないか確認する
            if not cart:
                messages.warning(request, "カートは空です")
                return redirect('main:user_cart')

            # 所持ポイントが十分にあるかを確認する。
            if total_price > user.point:
                messages.warning(request, "所持ポイントが足りません")
                return redirect('main:user_cart')

            # 在庫があるか確認する。
            for product, num in cart_products.items():
                if product.amount < num:
                    messages.warning(request, f"{product.name}の在庫が足りません")
                    return redirect('main:user_cart')

            # 各プロダクトのSale情報を保持（売上記録の登録）
            for product, num in cart_products.items():
                sale = Sale(
                    # modelでForeignKeyとしている為、productはProductのインスタンスでなければならない。
                    product=product,
                    user=user,
                    amount=num,
                    price=product.price,
                    zip_code=purchase_form.cleaned_data['zip_code'],
                    address=purchase_form.cleaned_data['address'],
                    # total_priceとしているが、商品ごとの小計
                    total_price=product.price * num,
                )

                # 在庫数変更
                product.amount -= num

                # データベースに保存
                sale.save()
                product.save()

                # 購入した分だけユーザーの保有ポイントを減らす。
                user.point -= total_price
                user.save()

            # セッションから'cart'を削除してカートを空にする
            del request.session['cart']

            messages.success(request, "商品の購入が完了しました！")
            return redirect('main:user_cart')

    # GETの場合
    purchase_form = PurchaseForm()

    context = {
        'purchase_form': purchase_form,
        'cart_products': cart_products,
        'total_price': total_price,
    }
    return render(request, template_name='main/user_cart.html', context=context)


# 数量変更
@login_required
@require_POST
def change_product_amount(request):
    # name="product_id"のフィールドの値を取得（どの商品を増減させるか）
    product_id = request.POST["product_id"]
    # セッションから"cart"情報を取得
    cart_session = request.session['cart']

    # センションの更新
    if product_id in cart_session:
        # １つ減らすボタンが押された時
        if "action_remove" in request.POST:
            cart_session[product_id] -= 1
        # １つ増やすボタンが押された時
        if "action_add" in request.POST:
            cart_session[product_id] += 1
        # 商品個数が0以下になった場合は、カートから対象商品の削除
        if cart_session[product_id] <= 0:
            del cart_session[product_id]
    return redirect('main:user_cart')


# 注文履歴
@login_required
def order_history(request):
    user = request.user
    sales = Sale.objects.filter(user=user).order_by('-created_at')
    context = {'sales': sales}
    return render(request, template_name='main/order_history.html',
                  context=context)


# 決済　支払いフォームを返す処理
def payment(request):
    # StripeのAPIキーを登録する
    stripe.api_key = settings.STRIPE_API_KEY

    # 今回は支払い額を10,000円とする
    amount = 10000

    # PaymentIntentを作成する
    intent = stripe.PaymentIntent.create(
        amount=amount,
        currency='jpy',
        description='テスト支払い',
        payment_method_types=["card"],
    )

    # 作成したPaymentIntentからclient_secretを取得する
    client_secret = intent["client_secret"]

    # テンプレートと渡すデータを指定する
    template_name = "payment.html"
    context = {
        "amount": amount,
        "client_secret": client_secret,
    }

    return render(request, template_name, context)


# 単純に支払い完了ページを表示する処理
def thanks(request):
    template_name = "thanks.html"
    return render(request, template_name)

main/templates/main/cart.html
{% extends 'base.html' %}

{% block content %}
<div class="cart-container">
    <div class="container">

        {% for product, num in cart_products.items %}
        <div class="card m-3" style="width: 35rem;">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    <img class="card-img cart-img" src="{{ product.image.url }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p>価格：{{ product.price }}円</p>
                        <p>数量：{{ num }}個</p>
                        <form action="{% url 'main:change_product_amount' %}"
                              method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="product_id"
                                   value="{{ product.id }}">
                            <input type="submit" name="action_remove"
                                   value="1つ減らす">
                            <input type="submit" name="action_add"
                                   value="1つ増やす">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="purchase-form m-3" style="width: 40rem;">
        <form method="POST">
            {% csrf_token %}
            <div class="purchase-form-container">
                <div class="purchase-form-address">
                    <div>
                        <p>
                            {{ purchase_form.zip_code.label_tag }}
                            {{ purchase_form.zip_code }}
                            <input type="submit" name="search_address"
                                   value="住所を検索">
                        </p>

                    </div>
                    <div>
                        <p>
                            {{ purchase_form.address.label_tag }}
                            {{ purchase_form.address }}
                        </p>
                    </div>
                </div>
                <div class="purchase-form-pay">
                    請求金額：{{ total_price }}
                    <input type="submit" name="buy_product"
                           class="purchase-button" value="購入する">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="carouselExampleCaptions" class="carousel slide"
     data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="0" class="active" aria-current="true"
                aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/aohaikei5.jpg' %}" class="d-block w-100"
                 alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h3>ポートフォリオ用です</h3>
                <p>お借りしたサイト</p>
                <p>https://chicodeza.com/freeitems/mizunohaikei.html</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/miromizuy2.jpg' %}" class="d-block w-100"
                 alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h3>ポートフォリオ用です</h3>
                <p>お借りしたサイト</p>
                <p>https://chicodeza.com/freeitems/mizunohaikei.html</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/mizuirohaikeiy1.jpg' %}"
                 class="d-block w-100"
                 alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h3>ポートフォリオ用です</h3>
                <p>お借りしたサイト</p>
                <p>https://chicodeza.com/freeitems/mizunohaikei.html</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button"
            data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button"
            data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>


<div class="container-fluid row">
    {% for page in pages %}
    <div class="card m-4 p-4" style="width: 18rem;">
        <img src="{{ page.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ page.name }}</h5>
            <p class="card-text">{{ page.price }}</p>
            <a href="{% url 'main:product_detail' page.id %}"
               class="btn btn-primary">商品詳細</a>
        </div>
    </div>
    {% endfor %}

    {% if pages.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if pages.has_previous %}
            <li><a class="page-link text-primary d-inline-block"
                   href="?page={{ pages.previous_page_number }}"><<</a></li>
            {% else %}
            <li class="disabled">
                <div class="page-link text-secondary d-inline-block disabled"
                     href="#"><<
                </div>
            </li>
            {% endif %}

            {% for page_num in pages.paginator.page_range %}
            {% if page_num %}
            {% if page_num == pages.number %}
            <li class="disabled">
                <div class="page-link text-secondary d-inline-block disabled"
                     href="#">{{ page_num }}
                </div>
            </li>
            {% else %}
            <li><a class="page-link text-primary d-inline-block"
                   href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
            {% else %}
            <li class="disabled"><a
                    class="page-link text-secondary d-inline-block text-muted"
                    href="#">・・・</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
    {% endif %}
{% endblock content %}

main/templates/main/order_history.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
<div class="container order-container">
    <div class="order-history mt-3">
        <h2>注文履歴</h2>
        {% for sale in sales %}
        <div class="card m-3" style="width: 35rem;">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    <img class="card-img cart-img"
                         src="{{ sale.product.image.url }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="order-content mb-1">
                        <h6 class="card-title">{{ sale.product.name }}</h6>
                        価格：{{ sale.price }}円
                        <br>
                        数量：{{ sale.amount }}個
                        <br>
                        合計金額：{{ sale.total_price }}円
                            </div>

                        <div class="order-address my-1">
                            <strong>お届け先住所</strong>
                            <br>
                            〒 {{ sale.zip_code }}
                            <br>
                            {{ sale.address }}
                        </div>
                        <div class="order-day mb-1">
                            <h6>注文日：{{ sale.created_at }}</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

main/templates/main/product_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<section class="wrapper">
    <div class="container">
        <div class="content">
            <div class="content-item">
                <img src="{{ product.image.url }}" class="image" style="wight: 18rem;">
            </div>
            <div class="content-item">
                <div class="text">
                    <h2 class="heading">商品名：{{ product.name }}</h2>
                    <p>商品説明：{{ product.description }}</p>
                    <p>価格：{{ product.price }}円</p>
                    {% if request.user.is_authenticated %}
                    <form method="POST">
                        {% csrf_token %}
                        {{ add_cart_form.as_p }}
                        <button type="submit">
                            カートに追加する
                        </button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

main/templates/main/test_index.html
{% extends 'base.html' %}

{% block content %}

<p>users</p>
{% for user in users %}
<p>{{ user }}</p>
{% endfor %}

<p>products</p>
{% for product in products %}
<p>{{ product }}</p>
{% endfor %}

<p>sales</p>
{% for sale in sales %}
<p>{{ sale }}</p>
{% endfor %}


{% endblock content %}

main/templates/main/user_cart.html
{% extends 'base.html' %}

{% block content %}
<div class="cart-container">
    <div class="container">

        {% for product, num in cart_products.items %}
        <div class="card m-3" style="width: 35rem;">
            <div class="row no-gutters">
                <div class="col-md-4 my-auto">
                    <img class="card-img cart-img" src="{{ product.image.url }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p>価格：{{ product.price }}円</p>
                        <p>数量：{{ num }}個</p>
                        <form action="{% url 'main:change_product_amount' %}"
                              method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="product_id"
                                   value="{{ product.id }}">
                            <input type="submit" name="action_remove"
                                   value="1つ減らす">
                            <input type="submit" name="action_add"
                                   value="1つ増やす">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="purchase-form m-3" style="width: 40rem;">
        <form method="POST">
            {% csrf_token %}
            <div class="purchase-form-container">
                <div class="purchase-form-address">
                    <div>
                        <p>
                            {{ purchase_form.zip_code.label_tag }}
                            {{ purchase_form.zip_code }}
                            <input type="submit" name="search_address"
                                   value="住所を検索">
                        </p>

                    </div>
                    <div>
                        <p>
                            {{ purchase_form.address.label_tag }}
                            {{ purchase_form.address }}
                        </p>
                    </div>
                </div>
                <div class="purchase-form-pay">
                    請求金額：{{ total_price }}
                    <input type="submit" name="buy_product"
                           class="purchase-button" value="購入する">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}